from pathlib import Path
import fwbuild
import fwbuild.ninja_syntax
import sys

def ninja(platform, buildfile_name: str | Path):
    buildfile_name = Path(buildfile_name)
    buildfile_name.parent.mkdir(parents=True, exist_ok=True)
    with open(buildfile_name, "w") as buildfile:
        w = fwbuild.ninja_syntax.Writer(buildfile)
        w.comment("DO NOT EDIT THIS FILE")
        w.comment("It is automatically generated by fwbuild using")
        w.comment(sys.modules["__main__"].__file__)
        w.newline()

        w.variable("topdir", fwbuild.topdir.as_posix())
        w.newline()

        if len(platform.targets) == 1:
            platform.write_buildfile(w, platform.targets[0])
        else:
            for target in platform.targets:
                name = buildfile_name.parent / f"{name}-build.ninja"
                with open(name, "w") as f:
                    n = fwbuild.ninja_syntax.Writer(f)
                    n.comment("DO NOT EDIT THIS FILE")
                    n.comment("It is automatically generated by fwbuild using")
                    n.comment(sys.modules["__main__"].__file__)
                    n.newline()
                    platform.write_buildfile(n, target)
                w.subninja(name.as_posix())
