name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: stamerlan/sandwich-build:latest

    strategy:
      matrix:
        platform: [host, raspi3b]
        include:
          - platform: host
            artifacts_name: host-binaries
            artifacts_path: bin/host/hello
          - platform: raspi3b
            artifacts_name: raspi3b-binaries
            artifacts_path: |
              bin/raspi3b/kernel8.elf
              bin/raspi3b/kernel8.bin

    steps:
    - name: Check out repo main branch
      uses: actions/checkout@v3
    - name: Configure
      run: python3 configure.py --config ${{ matrix.platform }}.config
    - name: Build
      run: ninja -C bin/${{ matrix.platform }}
    - name: Test
      run: ninja -C bin/${{ matrix.platform }} test
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifacts_name }}
        path: ${{ matrix.artifacts_path }}