name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: stamerlan/sandwich-build:latest
    steps:
    - name: Check out repo main branch
      uses: actions/checkout@v3
    - name: Configure
      run: python3 configure.py
    - name: Build
      run: ninja -C bin/
